<?php

class Type
{
    /** Numeric */
    const TINYINT = "TINYINT", MEDIUMINT = "MEDIUMINT", INT = "INT", BIGINT = "BIGINT", DECIMAL = "DECIMAL", FLOAT = "FLOAT", DOUBLE = "DOUBLE", REAL = "REAL", BIT = "BIT", BOOLEAN = "BOOLEAN", SERIAL = "SERIAL";

    /** Date & Time */
    const DATE = "DATE", DATETIME = "DATETIME", TIMESTAMP = "TIMESTAMP", TIME = "TIME", YEAR = "YEAR";

    /** String */
    const CHAR = "CHAR", VARCHAR = "VARCHAR", TINYTEXT = "TINYTEXT", TEXT = "TEXT", MEDIUMTEXT = "MEDIUMTEXT", LONGTEXT = "LONGTEXT", BINARY = "BINARY", VARBINARY = "VARBINARY", TINYBLOB = "TINYBLOB", MEDIUMBLOB = "MEDIUMBLOB", BLOB = "BLOB", LONGBLOB = "LONGBLOB", ENUM = "ENUM", SET = "SET";

    /** Spatial */
    const GEOMETRY = "GEOMETRY", POINT = "POINT", LINESTRING = "LINESTRING", POLYGON = "POLYGON", MULTIPOINT = "MULTIPOINT", MULTILINESTRING = "MULTILINESTRING", MULTIPOLYGON = "MULTIPOLYGON", GEOMETRYCOLLECTION = "GEOMETRYCOLLECTION";
}